"""Initial migration

Revision ID: e639b1acaa0c
Revises: 
Create Date: 2026-02-11 17:30:05.339370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e639b1acaa0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('shiprocket_order_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('billing_customer_name', sa.String(length=255), nullable=False),
    sa.Column('billing_city', sa.String(length=100), nullable=False),
    sa.Column('billing_pincode', sa.String(length=10), nullable=False),
    sa.Column('billing_state', sa.String(length=100), nullable=False),
    sa.Column('billing_country', sa.String(length=100), nullable=False),
    sa.Column('billing_phone', sa.String(length=20), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('order_items', sa.JSON(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('breadth', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('shiprocket_shipment_id', sa.Integer(), nullable=True),
    sa.Column('awb_code', sa.String(length=100), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('courier_name', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('estimated_delivery_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_status', sa.String(length=100), nullable=True),
    sa.Column('tracking_history', sa.JSON(), nullable=True),
    sa.Column('label_url', sa.String(length=500), nullable=True),
    sa.Column('invoice_url', sa.String(length=500), nullable=True),
    sa.Column('manifest_url', sa.String(length=500), nullable=True),
    sa.Column('pickup_scheduled', sa.Boolean(), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shiprocket_shipment_id')
    )
    op.create_index(op.f('ix_shipments_awb_code'), 'shipments', ['awb_code'], unique=True)
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_awb_code'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
